<a href="https://colab.research.google.com/github/youmnaayman21/iti-P/blob/main/T4_ITI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [2]:
# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 2: Import pandas
import pandas as pd
import numpy as np

file_path = '/content/drive/MyDrive/Data/Purchase_Data.csv'
df = pd.read_csv(file_path)


print("CSV file loaded successfully! Here are the first few rows:")
print(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
CSV file loaded successfully! Here are the first few rows:
   invoice_number   invoice_time store_id  product_id  category_id  num_item  \
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101       1.0
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203       1.0
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203       1.0
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401       1.0
4    2.020000e+11  7/15/15 12:16     G816     7090363        70401       1.0

   price
0    2.0
1    2.0
2    2.0
3    6.0
4    6.0

Use the dtypes attribute to view how each column is stored

In [3]:
#Write your code here
df.dtypes

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object



```
# This is formatted as code
```

Slice the first two columns using .loc and store the result in a variable called result_1.

In [4]:
#Write you code here
result_1 = df.loc[:, 'invoice_number':'invoice_time']
result_1

      invoice_number   invoice_time
0       2.020000e+11  7/15/15 10:45
1       2.020000e+11  7/15/15 12:16
2       2.020000e+11  7/15/15 12:16
3       2.020000e+11  7/15/15 12:16
4       2.020000e+11  7/15/15 12:16
...              ...            ...
5377    2.020000e+11   9/5/15 23:07
5378    2.020000e+11   9/5/15 23:23
5379    2.020000e+11   9/5/15 23:24
5380    2.020000e+11   9/5/15 23:32
5381    2.020000e+11   9/5/15 23:38

[5382 rows x 2 columns]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [5]:
#Write you code here
result_2 = df.loc[0:1, :]
result_2

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [6]:
#Write your code here
result_3 = df.iloc[:4, :5]
result_3

   invoice_number   invoice_time store_id  product_id  category_id
0    2.020000e+11  7/15/15 10:45     G816     7000300       210101
1    2.020000e+11  7/15/15 12:16     G816     7070884        70203
2    2.020000e+11  7/15/15 12:16     G816     7070884        70203
3    2.020000e+11  7/15/15 12:16     G816     7070891        70401

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [7]:
#Write your code here
result_4 = df.loc[[0, 4, 6], ['invoice_time', 'price']]
result_4

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [8]:
num_rows = df.shape[0]

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [9]:
#Write your code here
num_rows = df.shape[0]
last_row = df.iloc[num_rows - 1, :]
print(last_row)

invoice_number    202000000000.0
invoice_time        9/5/15 23:38
store_id                    G619
product_id              23030206
category_id               210101
num_item                     1.0
price                        2.0
Name: 5381, dtype: object

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [10]:
#Write your code here
avg_price = df['price'].mean()
max_price = df['price'].max()
print(avg_price)
print(max_price)

3.1920522110741363
6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [11]:
#Write you code here
avg_price = df['price'].mean()
avg_num_items = df['num_item'].mean()
print(avg_price)
print(avg_num_items)

3.1920522110741363
1.2983091787439613

Create a column called "total", which is the product of the price and num_item columns.

In [12]:
#Write your code here
df["total"] = df["price"] * df["num_item"]
df

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,total
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0,6.0
...,...,...,...,...,...,...,...,...
5377,2.020000e+11,9/5/15 23:07,300,7308017,210101,1.0,3.0,3.0
5378,2.020000e+11,9/5/15 23:23,G619,7070891,70401,1.0,6.0,6.0
5379,2.020000e+11,9/5/15 23:24,G619,7071096,70201,1.0,5.0,5.0
5380,2.020000e+11,9/5/15 23:32,G619,15000231,70301,2.0,2.0,4.0
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0,2.0

What is the avgerage price of the three most expensive purchases?

In [14]:
#Write your code here
avg_price_most_expensive = df.nlargest(3, 'price')['price'].mean()
avg_price_most_expensive

np.float64(6.003333333333333)

How many different products are there?

In [16]:
#Write your code here
num_products = df['product_id'].nunique()
num_products

53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [17]:
#Write your code here
df['total'].describe()

count    5382.000000
mean        3.931808
std         5.820520
min         0.000000
25%         2.000000
50%         3.000000
75%         5.000000
max       348.000000
Name: total, dtype: float64

Use the drop() method to delete the column total from the dataframe df_data.

In [18]:
#Write your code here
df = df.drop('total', axis=1)
df

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0
...,...,...,...,...,...,...,...
5377,2.020000e+11,9/5/15 23:07,300,7308017,210101,1.0,3.0
5378,2.020000e+11,9/5/15 23:23,G619,7070891,70401,1.0,6.0
5379,2.020000e+11,9/5/15 23:24,G619,7071096,70201,1.0,5.0
5380,2.020000e+11,9/5/15 23:32,G619,15000231,70301,2.0,2.0
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

Let's dig a little deeper into the data set and answer some basic question.

In [19]:
#Write your code here
df.describe()
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5382 entries, 0 to 5381
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_number  5382 non-null   float64
 1   invoice_time    5382 non-null   object
 2   store_id        5382 non-null   object
 3   product_id      5382 non-null   int64
 4   category_id     5382 non-null   int64
 5   num_item        5382 non-null   float64
 6   price           5382 non-null   float64
dtypes: float64(3), int64(2), object(2)
memory usage: 294.5+ KB

invoice_number    0
invoice_time      0
store_id          0
product_id        0
category_id       0
num_item          0
price             0
dtype: int64

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [21]:
#Write your code here
df['invoice_time'] = pd.to_datetime(df['invoice_time'])
df.dtypes

/tmp/ipython-input-741061053.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['invoice_time'] = pd.to_datetime(df['invoice_time'])

invoice_number           float64
invoice_time      datetime64[ns]
store_id                  object
product_id                 int64
category_id                int64
num_item                 float64
price                    float64
dtype: object

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [22]:
#Write your code here
df['DOW'] = df['invoice_time'].dt.day_name()
df['Month'] = df['invoice_time'].dt.month
df.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,DOW,Month
0,2.020000e+11,2015-07-15 10:45:00,G816,7000300,210101,1.0,2.0,Wednesday,7
1,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,7
2,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,7
3,2.020000e+11,2015-07-15 12:16:00,G816,7070891,70401,1.0,6.0,Wednesday,7
4,2.020000e+11,2015-07-15 12:16:00,G816,7090363,70401,1.0,6.0,Wednesday,7

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [23]:
#Write your code here
num_purchases_wed = df['DOW'].value_counts()['Wednesday']
num_purchases_wed

np.int64(959)

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [27]:
#Write your code here
#Write your code here
# Step 1: Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Step 2: Import pandas
import pandas as pd
import numpy as np

file_path = '/content/drive/MyDrive/Data/Titanic.csv'
df = pd.read_csv(file_path)


print("CSV file loaded successfully! Here are the first few rows:")
print(df.head())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
CSV file loaded successfully! Here are the first few rows:
   PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female
2          894       2                     Myles, Mr. Thomas Francis    male
3          895       3                              Wirz, Mr. Albert    male
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked
0  34.5      0      0   330911   7.8292   NaN        Q
1  47.0      1      0   363272   7.0000   NaN        S
2  62.0      0      0   240276   9.6875   NaN        Q
3  27.0      0      0   315154   8.6625   NaN        S
4  22.0      1      1  3101298  12.2875   NaN        S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [28]:
#Write your code here
df = df.rename(columns={'Name': 'Passenger_Name', 'Ticket': 'Ticket_Num'})
df.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Change the index of the df_titanic to the column PasengerID.

In [29]:
#Write your code here
df = df.set_index('PassengerId')
df.head()

,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Select the name of passenger 896

In [30]:
#Write your code here
df.loc[896, 'Passenger_Name']

'Hirvonen, Mrs. Alexander (Helga E Lindqvist)'

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [31]:
#Write your code here
df.reset_index(inplace=True)
df.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [32]:
#Write you code here
df.isnull().sum()

PassengerId         0
Pclass              0
Passenger_Name      0
Sex                 0
Age                86
SibSp               0
Parch               0
Ticket_Num          0
Fare                1
Cabin             327
Embarked            0
dtype: int64

Compute the avg age of passengers ignoring the missing data.

In [33]:
#Write your code here
df['Age'].mean()

np.float64(30.272590361445783)

Using the fillna() method replace the missing values in the Age column with the mean.

In [34]:
#Write your code here
df['Age'].fillna(df['Age'].mean(), inplace=True)
df.head()

/tmp/ipython-input-407682433.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [35]:
#Write your code here
df_sorted = df.sort_values(by='Age', ascending=False)
df_sorted.reset_index(drop=True, inplace=True)
df_sorted.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,988,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S
1,973,1,"Straus, Mr. Isidor",male,67.0,1,0,PC 17483,221.7792,C55 C57,S
2,1197,1,"Crosby, Mrs. Edward Gifford (Catherine Elizabe...",female,64.0,1,1,112901,26.5500,B26,S
3,1128,1,"Warren, Mr. Frank Manley",male,64.0,1,0,110813,75.2500,D37,C
4,1071,1,"Compton, Mrs. Alexander Taylor (Mary Eliza Ing...",female,64.0,0,2,PC 17756,83.1583,E45,C